/**
 * Basic track content cluster. Keep this module data-only so each cluster can
 * be authored and reviewed independently.
 */

import type { LevelInput } from '../../types';

const modalLevel: LevelInput = {
  id: 'b07',
  trackId: 'basic',
  number: 7,
  title: 'Modal verbs: can, could, must, should',
  topic: {
    title: 'Modal verbs: can, could, must, should',
    summary:
      'Modal verbs add meaning like ability, permission, obligation, and advice. They never change form and are always followed by the base verb.',
    rules: [
      {
        rule: 'modal_ability_permission',
        title: 'Ability and permission: can and could',
        explanation:
          "Use can for ability and permission in the present (She can swim; Can I go out?), and could for past ability or polite requests (When I was young, I could run fast; Could you help me?). Modals never add -s and take the base verb.",
        example: 'He can speak three languages. / Could I borrow your pen?',
      },
      {
        rule: 'modal_obligation_advice',
        title: 'Obligation and advice: must and should',
        explanation:
          "Use must for strong obligation or necessity (You must wear a seatbelt), mustn't for prohibition (You mustn't smoke here), should for advice (You should rest), and don't have to for absence of necessity (You don't have to pay).",
        example: 'You should drink more water. / You must not park here.',
      },
    ],
  },
  questions: [
    {
      id: 'b07q01',
      levelId: 'b07',
      rule: 'modal_ability_permission',
      prompt: 'She ___ speak three languages.',
      choices: ['cans', 'can to', 'can', 'is can'],
      correctIndex: 2,
      choiceExplanations: [
        "'Cans' is wrong: modals never add -s, even for he/she/it.",
        "'Can to' is wrong: modals are followed by the base verb without 'to'.",
        "'Can' is correct: 'can' expresses ability and is followed by the base verb 'speak'.",
        "'Is can' is wrong: 'can' is not used with 'is'.",
      ],
    },
    {
      id: 'b07q02',
      levelId: 'b07',
      rule: 'modal_ability_permission',
      prompt: 'When I was young, I ___ run very fast.',
      choices: ['can', 'could', 'caned', 'am'],
      correctIndex: 1,
      choiceExplanations: [
        "'Can' is wrong: 'can' expresses present ability, but this is about the past.",
        "'Could' is correct: 'could' expresses past ability.",
        "'Caned' is wrong: modals do not have past forms like '-ed'.",
        "'Am' is wrong: 'am' cannot express ability.",
      ],
    },
    {
      id: 'b07q03',
      levelId: 'b07',
      rule: 'modal_ability_permission',
      prompt: '___ I borrow your pen?',
      choices: ['Can', 'Cans', 'To can', 'Is'],
      correctIndex: 0,
      choiceExplanations: [
        "'Can' is correct: 'can' asks for permission in a present question.",
        "'Cans' is wrong: modals never add -s.",
        "'To can' is wrong: 'to' never precedes a modal.",
        "'Is' is wrong: 'is' cannot ask this permission question with 'borrow'.",
      ],
    },
    {
      id: 'b07q04',
      levelId: 'b07',
      rule: 'modal_ability_permission',
      prompt: 'He ___ swim when he was five.',
      choices: ['can', 'could', 'cans', 'is'],
      correctIndex: 1,
      choiceExplanations: [
        "'Can' is wrong: 'can' is present, but the swimming is in the past.",
        "'Could' is correct: 'could' expresses past ability.",
        "'Cans' is wrong: modals never add -s.",
        "'Is' is wrong: 'is' cannot express ability.",
      ],
    },
    {
      id: 'b07q05',
      levelId: 'b07',
      rule: 'modal_obligation_advice',
      prompt: 'You ___ wear a helmet on a motorbike.',
      choices: ['must', 'must to', 'can', 'is'],
      correctIndex: 0,
      choiceExplanations: [
        "'Must' is correct: 'must' expresses strong obligation.",
        "'Must to' is wrong: modals are followed by the base verb without 'to'.",
        "'Can' is wrong: 'can' expresses ability or permission, not a legal obligation.",
        "'Is' is wrong: 'is' cannot express obligation with 'wear'.",
      ],
    },
    {
      id: 'b07q06',
      levelId: 'b07',
      rule: 'modal_obligation_advice',
      prompt: 'You look tired. You ___ go to bed.',
      choices: ['must', 'should', 'can', 'is'],
      correctIndex: 1,
      choiceExplanations: [
        "'Must' is wrong: 'must' is too strong for a suggestion based on how someone looks.",
        "'Should' is correct: 'should' gives advice, which fits the situation.",
        "'Can' is wrong: 'can' expresses ability, not advice.",
        "'Is' is wrong: 'is' cannot form this advice sentence.",
      ],
    },
    {
      id: 'b07q07',
      levelId: 'b07',
      rule: 'modal_obligation_advice',
      prompt: 'You ___ smoke here — the sign says it’s forbidden.',
      choices: ['must to', 'don’t have to', 'is must', 'mustn’t'],
      correctIndex: 3,
      choiceExplanations: [
        "'Must to' is wrong: modals never take 'to'.",
        "'Don't have to' is wrong: that means 'it is not necessary', not 'it is forbidden'.",
        "'Is must' is wrong: 'is' is never combined with a modal.",
        "'Mustn't' is correct: 'mustn't' expresses prohibition.",
      ],
    },
    {
      id: 'b07q08',
      levelId: 'b07',
      rule: 'modal_obligation_advice',
      prompt: 'We ___ pay for the tickets; they’re free.',
      choices: ['don’t have to', 'mustn’t', 'must', 'should'],
      correctIndex: 0,
      choiceExplanations: [
        "'Don't have to' is correct: the tickets are free, so paying is not necessary.",
        "'Mustn't' is wrong: that means it is forbidden to pay, which is not the meaning.",
        "'Must' is wrong: 'must pay' means it is necessary, but the tickets are free.",
        "'Should' is wrong: 'should pay' would be advice, not a statement of no necessity.",
      ],
    },
    {
      id: 'b07q09',
      levelId: 'b07',
      rule: 'modal_obligation_advice',
      prompt: 'If you have a headache, you ___ take a rest.',
      choices: ['should', 'should to', 'is should', 'can to'],
      correctIndex: 0,
      choiceExplanations: [
        "'Should' is correct: 'should' gives advice, which fits a health suggestion.",
        "'Should to' is wrong: modals are followed by the base verb without 'to'.",
        "'Is should' is wrong: 'is' is never combined with a modal.",
        "'Can to' is wrong: 'to' never follows a modal.",
      ],
    },
    {
      id: "b07q10",
      levelId: "b07",
      rule: "modal_obligation_advice",
      type: 'fix_sentence',
      faultySentence: "If you have a headache, you should take a rest.",
      prompt: "If you have a headache, you ___ take a rest.",
      choices: ["should", "should to", "must to", "are should"],
      correctIndex: 0,
      choiceExplanations: ["'should' is correct: the sentence requires 'should'.", "'should to' is wrong: the sentence requires 'should'.", "'must to' is wrong: the sentence requires 'should'.", "'are should' is wrong: the sentence requires 'should'."],
    },
    {
      id: "b07q11",
      levelId: "b07",
      rule: "modal_obligation_advice",
      type: 'fill_blank',
      prompt: "You ___ wear a seat belt in a car.",
      correctAnswer: "must",
      acceptedAnswers: ["must"],
      explanation: "A modal is followed directly by the base verb; must expresses obligation.",
    },
    {
      id: "b07q12",
      levelId: "b07",
      rule: "modal_obligation_advice",
      type: 'word_order',
      sentenceWords: ["You", "should", "call", "your", "doctor."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "A modal is followed directly by the base verb; must expresses obligation.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 8 — Articles: a/an/the
// ─────────────────────────────────────────────────────────────────────────────

const articlesLevel: LevelInput = {
  id: 'b08',
  trackId: 'basic',
  number: 8,
  title: 'Articles: a, an, the',
  topic: {
    title: 'Articles: a, an, the',
    summary:
      'Use a or an for one non-specific thing, the for something specific or already known, and no article for general plurals and uncountable nouns.',
    rules: [
      {
        rule: 'articles_a_an',
        title: 'a vs an',
        explanation:
          "Use a before a consonant sound and an before a vowel sound: a book, an apple, an hour (h is silent), a university (starts with a 'y' sound). The choice follows the sound, not the letter.",
        example: 'She is a teacher. / He waited for an hour.',
      },
      {
        rule: 'articles_the_zero',
        title: 'the vs no article',
        explanation:
          "Use the when the listener knows which one — something specific or unique (the sun, the book I told you about). Use no article for general plurals and uncountable nouns (Dogs are loyal; I love music).",
        example: 'The water in this glass is cold. / Cats like milk.',
      },
    ],
  },
  questions: [
    {
      id: 'b08q01',
      levelId: 'b08',
      rule: 'articles_a_an',
      prompt: 'I saw ___ elephant at the zoo.',
      choices: ['a', 'an', 'the', 'nothing'],
      correctIndex: 1,
      choiceExplanations: [
        "'A' is wrong: 'elephant' starts with a vowel sound, so it takes 'an'.",
        "'An' is correct: 'elephant' begins with a vowel sound.",
        "'The' is wrong: 'the' would mean a specific, known elephant, but this is the first mention.",
        "'Nothing' is wrong: a singular countable noun like 'elephant' needs an article.",
      ],
    },
    {
      id: 'b08q02',
      levelId: 'b08',
      rule: 'articles_a_an',
      prompt: 'She is ___ doctor.',
      choices: ['a', 'an', 'the', 'nothing'],
      correctIndex: 0,
      choiceExplanations: [
        "'A' is correct: 'doctor' starts with a consonant sound and is one non-specific doctor.",
        "'An' is wrong: 'an' is used before vowel sounds, and 'doctor' begins with a consonant.",
        "'The' is wrong: 'the' would name a specific doctor, but we are naming her profession.",
        "'Nothing' is wrong: a singular countable noun naming a job needs an article.",
      ],
    },
    {
      id: 'b08q03',
      levelId: 'b08',
      rule: 'articles_a_an',
      prompt: 'He waited for ___ hour.',
      choices: ['a', 'an', 'the', 'nothing'],
      correctIndex: 1,
      choiceExplanations: [
        "'A' is wrong: in 'hour', the 'h' is silent, so the word starts with a vowel sound and takes 'an'.",
        "'An' is correct: 'hour' starts with a vowel sound (silent 'h').",
        "'The' is wrong: 'the' would mean a specific known hour, but this is one hour in general.",
        "'Nothing' is wrong: a singular countable noun like 'hour' needs an article.",
      ],
    },
    {
      id: 'b08q04',
      levelId: 'b08',
      rule: 'articles_a_an',
      prompt: 'They live in ___ university town.',
      choices: ['a', 'an', 'the', 'nothing'],
      correctIndex: 0,
      choiceExplanations: [
        "'A' is correct: 'university' starts with a 'y' (consonant) sound, so it takes 'a'.",
        "'An' is wrong: 'university' starts with a consonant sound despite its first letter being 'u'.",
        "'The' is wrong: 'the' would mean a specific known town, but this is one university town in general.",
        "'Nothing' is wrong: 'town' is a singular countable noun and needs an article.",
      ],
    },
    {
      id: 'b08q05',
      levelId: 'b08',
      rule: 'articles_a_an',
      prompt: 'We need ___ umbrella.',
      choices: ['a', 'an', 'the', 'nothing'],
      correctIndex: 1,
      choiceExplanations: [
        "'A' is wrong: 'umbrella' starts with a vowel sound, so it takes 'an'.",
        "'An' is correct: 'umbrella' begins with a vowel sound.",
        "'The' is wrong: 'the' would mean a specific umbrella already known, but this is any umbrella.",
        "'Nothing' is wrong: a singular countable noun like 'umbrella' needs an article.",
      ],
    },
    {
      id: 'b08q06',
      levelId: 'b08',
      rule: 'articles_the_zero',
      prompt: 'I love ___ music.',
      choices: ['the', 'a', 'an', 'nothing'],
      correctIndex: 3,
      choiceExplanations: [
        "'The' is wrong: 'the music' would mean specific music, but here music is a general idea.",
        "'A' is wrong: 'music' is uncountable and cannot take 'a'.",
        "'An' is wrong: 'an' is for singular countable nouns, and 'music' is uncountable.",
        "'Nothing' is correct: uncountable nouns in a general meaning take no article.",
      ],
    },
    {
      id: 'b08q07',
      levelId: 'b08',
      rule: 'articles_the_zero',
      prompt: '___ sun rises in the east.',
      choices: ['A', 'An', 'The', 'nothing'],
      correctIndex: 2,
      choiceExplanations: [
        "'A' is wrong: there is only one sun, so the definite article fits.",
        "'An' is wrong: 'an' is for non-specific singular nouns with vowel sounds.",
        "'The' is correct: the sun is unique, so it takes 'the'.",
        "'Nothing' is wrong: a unique noun like 'sun' needs the definite article.",
      ],
    },
    {
      id: 'b08q08',
      levelId: 'b08',
      rule: 'articles_the_zero',
      prompt: '___ water in this glass is cold.',
      choices: ['A', 'An', 'The', 'nothing'],
      correctIndex: 2,
      choiceExplanations: [
        "'A' is wrong: 'water' is uncountable and cannot take 'a'.",
        "'An' is wrong: 'an' is for singular countable nouns.",
        "'The' is correct: we mean the specific water in this glass, so 'the' fits.",
        "'Nothing' is wrong: no article would mean water in general, but we mean this specific glass.",
      ],
    },
    {
      id: 'b08q09',
      levelId: 'b08',
      rule: 'articles_the_zero',
      prompt: '___ dogs are loyal animals.',
      choices: ['The', 'A', 'An', 'nothing'],
      correctIndex: 3,
      choiceExplanations: [
        "'The' is wrong: 'the dogs' would mean particular dogs, but this is about dogs in general.",
        "'A' is wrong: 'dogs' is plural and cannot take 'a'.",
        "'An' is wrong: 'an' is for singular countable nouns.",
        "'Nothing' is correct: general plural nouns take no article.",
      ],
    },
    {
      id: "b08q10",
      levelId: "b08",
      rule: "articles_the_zero",
      type: 'fix_sentence',
      faultySentence: "The water in this glass is cold.",
      prompt: "___ water in this glass is cold.",
      choices: ["The", "A", "An", "nothing"],
      correctIndex: 0,
      choiceExplanations: ["'The' is correct: the sentence requires 'The'.", "'A' is wrong: the sentence requires 'The'.", "'An' is wrong: the sentence requires 'The'.", "'nothing' is wrong: the sentence requires 'The'."],
    },
    {
      id: "b08q11",
      levelId: "b08",
      rule: "articles_the_zero",
      type: 'fill_blank',
      prompt: "She is ___ honest person.",
      correctAnswer: "an",
      acceptedAnswers: ["an"],
      explanation: "Use the before a specific noun and an before a vowel sound.",
    },
    {
      id: "b08q12",
      levelId: "b08",
      rule: "articles_the_zero",
      type: 'word_order',
      sentenceWords: ["The", "children", "are", "at", "school."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "Use the before a specific noun and an before a vowel sound.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 9 — Comparatives and Superlatives
// ─────────────────────────────────────────────────────────────────────────────

const comparativesLevel: LevelInput = {
  id: 'b09',
  trackId: 'basic',
  number: 9,
  title: 'Comparatives and Superlatives',
  topic: {
    title: 'Comparatives and Superlatives',
    summary:
      'Use the comparative to compare two things (taller, more expensive) and the superlative for three or more (the tallest, the most expensive).',
    rules: [
      {
        rule: 'comparatives',
        title: 'Form: -er or more + adjective',
        explanation:
          "Short adjectives add -er (tall → taller, big → bigger); longer adjectives use more (more expensive). Always compare with than (She is taller than me). Irregulars: good → better, bad → worse, far → farther.",
        example: 'This box is heavier than that one.',
      },
      {
        rule: 'superlatives',
        title: 'Form: the -est or the most + adjective',
        explanation:
          "Short adjectives add -est (tall → tallest, big → biggest); longer adjectives use the most (the most expensive). The superlative always takes the and usually mentions a group (the tallest in the class). Irregulars: good → best, bad → worst.",
        example: 'She is the best student in the class.',
      },
    ],
  },
  questions: [
    {
      id: 'b09q01',
      levelId: 'b09',
      rule: 'comparatives',
      prompt: 'A car is ___ than a bicycle.',
      choices: ['faster', 'more fast', 'fastest', 'fast'],
      correctIndex: 0,
      choiceExplanations: [
        "'Faster' is correct: short adjectives like 'fast' add -er in the comparative.",
        "'More fast' is wrong: 'more' is used with longer adjectives, not with a short one like 'fast'.",
        "'Fastest' is wrong: the superlative compares three or more, but this compares two things.",
        "'Fast' is wrong: the base form does not make a comparison with 'than'.",
      ],
    },
    {
      id: 'b09q02',
      levelId: 'b09',
      rule: 'comparatives',
      prompt: 'This book is ___ than that one.',
      choices: ['interestinger', 'more interesting', 'most interesting', 'interesting'],
      correctIndex: 1,
      choiceExplanations: [
        "'Interestinger' is wrong: long adjectives do not add -er.",
        "'More interesting' is correct: long adjectives like 'interesting' use 'more' in the comparative.",
        "'Most interesting' is wrong: 'most' is the superlative, but this compares just two books.",
        "'Interesting' is wrong: the base form does not make a comparison with 'than'.",
      ],
    },
    {
      id: 'b09q03',
      levelId: 'b09',
      rule: 'comparatives',
      prompt: 'My brother is taller ___ me.',
      choices: ['then', 'as', 'than', 'to'],
      correctIndex: 2,
      choiceExplanations: [
        "'Then' is wrong: 'then' is a time word; comparisons need 'than'.",
        "'As' is wrong: 'as' makes an equal comparison (as tall as), not a comparative.",
        "'Than' is correct: comparatives introduce the second item with 'than'.",
        "'To' is wrong: 'to' does not follow a comparative adjective.",
      ],
    },
    {
      id: 'b09q04',
      levelId: 'b09',
      rule: 'comparatives',
      prompt: 'Today is ___ than yesterday.',
      choices: ['hoter', 'more hot', 'hotter', 'hottest'],
      correctIndex: 2,
      choiceExplanations: [
        "'Hoter' is wrong: a short vowel-consonant word like 'hot' doubles the consonant before -er.",
        "'More hot' is wrong: 'more' is used with longer adjectives, not with 'hot'.",
        "'Hotter' is correct: 'hot' doubles the final consonant and adds -er.",
        "'Hottest' is wrong: the superlative compares three or more, not two days.",
      ],
    },
    {
      id: 'b09q05',
      levelId: 'b09',
      rule: 'superlatives',
      prompt: 'This is the ___ day of the year.',
      choices: ['hot', 'hotter', 'more hot', 'hottest'],
      correctIndex: 3,
      choiceExplanations: [
        "'Hot' is wrong: the base form does not compare within a group.",
        "'Hotter' is wrong: the comparative compares two; 'of the year' is a group of many.",
        "'More hot' is wrong: 'more' is not used with a short adjective like 'hot'.",
        "'Hottest' is correct: the superlative (the -est form) names the top of the group.",
      ],
    },
    {
      id: 'b09q06',
      levelId: 'b09',
      rule: 'superlatives',
      prompt: 'She is the ___ student in the class.',
      choices: ['most smart', 'smartest', 'smarter', 'smart'],
      correctIndex: 1,
      choiceExplanations: [
        "'Most smart' is wrong: short adjectives like 'smart' take -est, not 'most'.",
        "'Smartest' is correct: the superlative of a short adjective is the + adjective + -est.",
        "'Smarter' is wrong: the comparative compares two, not a whole class.",
        "'Smart' is wrong: the base form does not show rank in a group.",
      ],
    },
    {
      id: 'b09q07',
      levelId: 'b09',
      rule: 'superlatives',
      prompt: 'It was the ___ film I have ever seen.',
      choices: ['most boring', 'boringer', 'more boring', 'boring'],
      correctIndex: 0,
      choiceExplanations: [
        "'Most boring' is correct: long adjectives like 'boring' form the superlative with 'the most'.",
        "'Boringer' is wrong: long adjectives do not add -er.",
        "'More boring' is wrong: 'more' is the comparative; 'ever seen' signals the superlative.",
        "'Boring' is wrong: the base form does not rank within a group.",
      ],
    },
    {
      id: 'b09q08',
      levelId: 'b09',
      rule: 'superlatives',
      prompt: 'Tokyo is one of the ___ cities in the world.',
      choices: ['larger', 'largest', 'large', 'more large'],
      correctIndex: 1,
      choiceExplanations: [
        "'Larger' is wrong: the comparative compares two, but this is about all the cities in the world.",
        "'Largest' is correct: the superlative ranks Tokyo among all cities.",
        "'Large' is wrong: the base form does not show rank.",
        "'More large' is wrong: short adjectives take -est in the superlative, not 'more'.",
      ],
    },
    {
      id: 'b09q09',
      levelId: 'b09',
      rule: 'comparatives',
      prompt: 'This bag is ___ than mine.',
      choices: ['expensiveer', 'most expensive', 'more expensive', 'expensive'],
      correctIndex: 2,
      choiceExplanations: [
        "'Expensiveer' is wrong: long adjectives do not add -er.",
        "'Most expensive' is wrong: 'most' is the superlative, but this compares two bags.",
        "'More expensive' is correct: a long adjective like 'expensive' forms the comparative with 'more'.",
        "'Expensive' is wrong: the base form does not make a comparison with 'than'.",
      ],
    },
    {
      id: "b09q10",
      levelId: "b09",
      rule: "superlatives",
      type: 'fix_sentence',
      faultySentence: "Of the three roads, this one is the longest.",
      prompt: "Of the three roads, this one is the ___.",
      choices: ["longest", "longer", "long", "more long"],
      correctIndex: 0,
      choiceExplanations: ["'longest' is correct: the sentence requires 'longest'.", "'longer' is wrong: the sentence requires 'longest'.", "'long' is wrong: the sentence requires 'longest'.", "'more long' is wrong: the sentence requires 'longest'."],
    },
    {
      id: "b09q11",
      levelId: "b09",
      rule: "superlatives",
      type: 'fill_blank',
      prompt: "This bag is ___ than mine.",
      correctAnswer: "more expensive",
      acceptedAnswers: ["more expensive"],
      explanation: "Comparatives compare two things; superlatives rank one within a group.",
    },
    {
      id: "b09q12",
      levelId: "b09",
      rule: "superlatives",
      type: 'word_order',
      sentenceWords: ["This", "is", "the", "best", "option."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "Comparatives compare two things; superlatives rank one within a group.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 10 — Past Perfect (the Task 4 reference level, renumbered to 10)
// ─────────────────────────────────────────────────────────────────────────────

const pastPerfectLevel: LevelInput = {
  id: 'b10',
  trackId: 'basic',
  number: 10,
  title: 'Past Perfect',
  topic: {
    title: 'Past Perfect',
    summary: 'The past perfect describes an action completed before another past action.',
    rules: [
      {
        rule: 'past_perfect_form',
        title: 'Form: had + past participle',
        explanation: "Formed with 'had' + the past participle (worked, gone, seen).",
        example: 'They had finished dinner before we arrived.',
      },
      {
        rule: 'past_perfect_vs_past_simple',
        title: 'Past Perfect vs Past Simple',
        explanation: 'Use past simple for the later action and past perfect for the earlier one.',
        example: 'The train had left (earlier) by the time we arrived (later).',
      },
    ],
  },
  questions: [
    // ── past_perfect_form ──────────────────────────────────────────────
    {
      id: 'b10q01',
      levelId: 'b10',
      rule: 'past_perfect_form',
      prompt: 'By the time we arrived, the movie ___ .',
      choices: ['starts', 'had started', 'started', 'was started'],
      correctIndex: 1,
      choiceExplanations: [
        "'Starts' is present simple — wrong tense for a past event.",
        "'Had started' is correct: past perfect ('had' + past participle) marks the action as completed before we arrived.",
        "'Started' is past simple — it does not mark the movie as finished before the later past action.",
        "'Was started' is passive voice — wrong; the movie began, it was not begun by someone.",
      ],
    },
    {
      id: 'b10q02',
      levelId: 'b10',
      rule: 'past_perfect_form',
      prompt: 'She ___ her keys before leaving the house.',
      choices: ['locks', 'had locked', 'locked', 'has locked'],
      correctIndex: 1,
      choiceExplanations: [
        "'Locks' is present simple — wrong tense for a past event.",
        "'Had locked' is correct: the locking happened before the leaving, so past perfect fits.",
        "'Locked' is past simple — it does not mark the locking as earlier than the leaving.",
        "'Has locked' is present perfect — wrong; the leaving is a past event, so the earlier action needs past perfect.",
      ],
    },
    {
      id: 'b10q03',
      levelId: 'b10',
      rule: 'past_perfect_form',
      prompt: "The children ___ asleep by nine o'clock.",
      choices: ['fell', 'have fallen', 'had fallen', 'fall'],
      correctIndex: 2,
      choiceExplanations: [
        "'Fell' is past simple — it does not mark the falling asleep as completed by a past time.",
        "'Have fallen' is present perfect — wrong; nine o'clock is a past reference point.",
        "'Had fallen' is correct: past perfect for the action completed before a past time (nine o'clock).",
        "'Fall' is present simple — wrong tense for a past event.",
      ],
    },
    {
      id: 'b10q04',
      levelId: 'b10',
      rule: 'past_perfect_form',
      prompt: 'When I called, he ___ .',
      choices: ['already left', 'was already leaving', 'had already left', 'has already left'],
      correctIndex: 2,
      choiceExplanations: [
        "'Already left' is past simple — the leaving is not marked as earlier than the call.",
        "'Was already leaving' is past continuous — wrong; it shows the leaving in progress, not completed before the call.",
        "'Had already left' is correct: past perfect marks the leaving as completed before I called.",
        "'Has already left' is present perfect — wrong; the call is a past event, not a present one.",
      ],
    },
    {
      id: 'b10q05',
      levelId: 'b10',
      rule: 'past_perfect_form',
      prompt: 'After they ___, the meeting began.',
      choices: ['were sitting', 'sat down', 'have sat down', 'had sat down'],
      correctIndex: 3,
      choiceExplanations: [
        "'Were sitting' is past continuous — wrong; the meaning here is a completed action, not one in progress.",
        "'Sat down' is past simple — it does not mark the sitting as earlier than the meeting.",
        "'Have sat down' is present perfect — wrong; the meeting began in the past.",
        "'Had sat down' is correct: past perfect for the action completed before the meeting began.",
      ],
    },
    {
      id: 'b10q06',
      levelId: 'b10',
      rule: 'past_perfect_form',
      prompt: 'I ___ that place before, so I knew my way around.',
      choices: ['visited', 'had visited', 'was visiting', 'have visited'],
      correctIndex: 1,
      choiceExplanations: [
        "'Visited' is past simple — it does not mark the visit as earlier than the knowing.",
        "'Had visited' is correct: past perfect for the earlier visit, which explains the later knowing.",
        "'Was visiting' is past continuous — wrong; the visit is a completed earlier event.",
        "'Have visited' is present perfect — wrong; the following clause is in the past.",
      ],
    },
    // ── past_perfect_vs_past_simple ────────────────────────────────────
    {
      id: 'b10q07',
      levelId: 'b10',
      rule: 'past_perfect_vs_past_simple',
      prompt: 'By the time we got to the station, the train ___ .',
      choices: ['left', 'had left', 'has left', 'leaves'],
      correctIndex: 1,
      choiceExplanations: [
        "'Left' is past simple — fine for the later action, but the departure happened before we arrived, so the earlier action needs past perfect.",
        "'Had left' is correct: past perfect marks the earlier of two past actions.",
        "'Has left' is present perfect — wrong here; the departure is a completed past event before another past event.",
        "'Leaves' is present simple — wrong tense for any past context.",
      ],
    },
    {
      id: 'b10q08',
      levelId: 'b10',
      rule: 'past_perfect_vs_past_simple',
      prompt: 'She ___ her keys before I asked.',
      choices: ['already found', 'has already found', 'had already found', 'finds'],
      correctIndex: 2,
      choiceExplanations: [
        "'Already found' is past simple — the finding still needs to be marked as earlier than the asking.",
        "'Has already found' is present perfect — wrong; the asking is a past event, not a present one.",
        "'Had already found' is correct: past perfect for the action completed before the asking.",
        "'Finds' is present simple — wrong tense here.",
      ],
    },
    {
      id: 'b10q09',
      levelId: 'b10',
      rule: 'past_perfect_vs_past_simple',
      prompt: 'The waiter ___ our order before the kitchen closed.',
      choices: ['took', 'has taken', 'had taken', 'takes'],
      correctIndex: 2,
      choiceExplanations: [
        "'Took' is past simple — it does not mark the taking as earlier than the closing.",
        "'Has taken' is present perfect — wrong; the kitchen closed in the past.",
        "'Had taken' is correct: past perfect for the earlier action; the closing is the later past action.",
        "'Takes' is present simple — wrong tense for past events.",
      ],
    },
    {
      id: "b10q10",
      levelId: "b10",
      rule: "past_perfect_vs_past_simple",
      type: 'fix_sentence',
      faultySentence: "The waiter had taken our order before the kitchen closed.",
      prompt: "The waiter ___ our order before the kitchen closed.",
      choices: ["had taken", "took", "has taken", "takes"],
      correctIndex: 0,
      choiceExplanations: ["'had taken' is correct: the sentence requires 'had taken'.", "'took' is wrong: the sentence requires 'had taken'.", "'has taken' is wrong: the sentence requires 'had taken'.", "'takes' is wrong: the sentence requires 'had taken'."],
    },
    {
      id: "b10q11",
      levelId: "b10",
      rule: "past_perfect_vs_past_simple",
      type: 'fill_blank',
      prompt: "She ___ her keys before I asked.",
      correctAnswer: "had found",
      acceptedAnswers: ["had found"],
      explanation: "Use the past perfect for the earlier of two past actions.",
    },
    {
      id: "b10q12",
      levelId: "b10",
      rule: "past_perfect_vs_past_simple",
      type: 'word_order',
      sentenceWords: ["They", "had", "left", "before", "we", "arrived."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "Use the past perfect for the earlier of two past actions.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 11 — Prepositions of time
// ─────────────────────────────────────────────────────────────────────────────

const prepositionsTimeLevel: LevelInput = {
  id: 'b11',
  trackId: 'basic',
  number: 11,
  title: 'Prepositions of time',
  topic: {
    title: 'Prepositions of time',
    summary:
      'Prepositions of time connect an event to a time: at for clock times, on for days and dates, in for months, years, and parts of the day.',
    rules: [
      {
        rule: 'prepositions_time_in_on_at',
        title: 'in, on, at',
        explanation:
          "Use in with months, years, seasons, and parts of the day (in June, in 2020, in the morning); on with days and dates (on Monday, on 15 June); and at with clock times and 'night' (at six, at night).",
        example: 'The meeting is on Friday at three in the afternoon.',
      },
      {
        rule: 'prepositions_time_since_for_until',
        title: 'since, for, until',
        explanation:
          "Use since with a starting point (since 2018), for with a duration (for three years), and until/till for the end of a period (open until nine).",
        example: 'I have worked here since 2018, for almost seven years.',
      },
    ],
  },
  questions: [
    {
      id: 'b11q01',
      levelId: 'b11',
      rule: 'prepositions_time_in_on_at',
      prompt: 'The meeting is ___ Monday.',
      choices: ['in', 'at', 'for', 'on'],
      correctIndex: 3,
      choiceExplanations: [
        "'In' is wrong: 'in' is for months and years, not for days.",
        "'At' is wrong: 'at' is for clock times, not days.",
        "'For' is wrong: 'for' expresses a duration, not a day.",
        "'On' is correct: days of the week take 'on'.",
      ],
    },
    {
      id: 'b11q02',
      levelId: 'b11',
      rule: 'prepositions_time_in_on_at',
      prompt: 'I was born ___ 1995.',
      choices: ['at', 'on', 'in', 'since'],
      correctIndex: 2,
      choiceExplanations: [
        "'At' is wrong: 'at' is for clock times, not years.",
        "'On' is wrong: 'on' is for days and dates, not years.",
        "'In' is correct: years take 'in'.",
        "'Since' is wrong: 'since' marks a starting point for a continuing period, not a birth year.",
      ],
    },
    {
      id: 'b11q03',
      levelId: 'b11',
      rule: 'prepositions_time_in_on_at',
      prompt: 'The bus leaves ___ six o’clock.',
      choices: ['on', 'in', 'at', 'until'],
      correctIndex: 2,
      choiceExplanations: [
        "'On' is wrong: 'on' is for days and dates, not clock times.",
        "'In' is wrong: 'in' is for months, years, and parts of the day.",
        "'At' is correct: clock times take 'at'.",
        "'Until' is wrong: 'until' marks an end point, not a departure time.",
      ],
    },
    {
      id: 'b11q04',
      levelId: 'b11',
      rule: 'prepositions_time_in_on_at',
      prompt: 'We have dinner ___ the evening.',
      choices: ['in', 'on', 'at', 'for'],
      correctIndex: 0,
      choiceExplanations: [
        "'In' is correct: parts of the day take 'in' (in the evening).",
        "'On' is wrong: 'on' is for days and dates, not parts of the day.",
        "'At' is wrong: 'at' is for clock times and 'at night'.",
        "'For' is wrong: 'for' expresses a duration.",
      ],
    },
    {
      id: 'b11q05',
      levelId: 'b11',
      rule: 'prepositions_time_in_on_at',
      prompt: 'She was born ___ the 15th of June.',
      choices: ['at', 'on', 'in', 'until'],
      correctIndex: 1,
      choiceExplanations: [
        "'At' is wrong: 'at' is for clock times, not dates.",
        "'On' is correct: specific dates take 'on'.",
        "'In' is wrong: 'in' is for months and years, not a single date.",
        "'Until' is wrong: 'until' marks an end point, not a birth date.",
      ],
    },
    {
      id: 'b11q06',
      levelId: 'b11',
      rule: 'prepositions_time_in_on_at',
      prompt: 'They visit us ___ night.',
      choices: ['at', 'on', 'in', 'since'],
      correctIndex: 0,
      choiceExplanations: [
        "'At' is correct: 'at night' is a fixed expression.",
        "'On' is wrong: 'on' is for days and dates.",
        "'In' is wrong: 'in the night' is not the standard expression; the fixed form is 'at night'.",
        "'Since' is wrong: 'since' marks a starting point, not a time of day.",
      ],
    },
    {
      id: 'b11q07',
      levelId: 'b11',
      rule: 'prepositions_time_since_for_until',
      prompt: 'I have studied English ___ three years.',
      choices: ['since', 'for', 'until', 'on'],
      correctIndex: 1,
      choiceExplanations: [
        "'Since' is wrong: 'since' needs a starting point, not a length of time.",
        "'For' is correct: a duration ('three years') takes 'for'.",
        "'Until' is wrong: 'until' marks an end point, not a duration.",
        "'On' is wrong: 'on' is for days and dates.",
      ],
    },
    {
      id: 'b11q08',
      levelId: 'b11',
      rule: 'prepositions_time_since_for_until',
      prompt: 'She has lived here ___ 2018.',
      choices: ['for', 'since', 'until', 'at'],
      correctIndex: 1,
      choiceExplanations: [
        "'For' is wrong: 'for' needs a duration, but '2018' is a starting point.",
        "'Since' is correct: a starting point in time ('2018') takes 'since'.",
        "'Until' is wrong: 'until' marks an end point, but she still lives here.",
        "'At' is wrong: 'at' is for clock times, not years.",
      ],
    },
    {
      id: 'b11q09',
      levelId: 'b11',
      rule: 'prepositions_time_since_for_until',
      prompt: 'The shop is open ___ nine o’clock.',
      choices: ['since', 'for', 'until', 'in'],
      correctIndex: 2,
      choiceExplanations: [
        "'Since' is wrong: 'since' needs a starting point.",
        "'For' is wrong: 'for' needs a duration, not an end time.",
        "'Until' is correct: 'until' marks the end of the opening time.",
        "'In' is wrong: 'in' is for months, years, and parts of the day.",
      ],
    },
    {
      id: "b11q10",
      levelId: "b11",
      rule: "prepositions_time_since_for_until",
      type: 'fix_sentence',
      faultySentence: "The shop is open until nine o\u2019clock.",
      prompt: "The shop is open ___ nine o\u2019clock.",
      choices: ["until", "since", "for", "in"],
      correctIndex: 0,
      choiceExplanations: ["'until' is correct: the sentence requires 'until'.", "'since' is wrong: the sentence requires 'until'.", "'for' is wrong: the sentence requires 'until'.", "'in' is wrong: the sentence requires 'until'."],
    },
    {
      id: "b11q11",
      levelId: "b11",
      rule: "prepositions_time_since_for_until",
      type: 'fill_blank',
      prompt: "We waited ___ two hours.",
      correctAnswer: "for",
      acceptedAnswers: ["for"],
      explanation: "Use for with a duration, since with a starting point, and until with an end point.",
    },
    {
      id: "b11q12",
      levelId: "b11",
      rule: "prepositions_time_since_for_until",
      type: 'word_order',
      sentenceWords: ["She", "has", "lived", "here", "since", "2018."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "Use for with a duration, since with a starting point, and until with an end point.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 12 — Zero and First Conditionals
// ─────────────────────────────────────────────────────────────────────────────

const conditionalsLevel: LevelInput = {
  id: 'b12',
  trackId: 'basic',
  number: 12,
  title: 'Zero and First Conditionals',
  topic: {
    title: 'Zero and First Conditionals',
    summary:
      'Conditionals link a condition to a result. The zero conditional states general truths; the first conditional talks about a real possibility in the future.',
    rules: [
      {
        rule: 'zero_conditional',
        title: 'Zero conditional: if + present simple, present simple',
        explanation:
          'Use the zero conditional for facts and general truths: if/when + present simple, then present simple (If you heat ice, it melts). Both clauses describe something always true.',
        example: 'If you mix red and blue, you get purple.',
      },
      {
        rule: 'first_conditional',
        title: 'First conditional: if + present simple, will + base verb',
        explanation:
          "Use the first conditional for a real possibility in the future: the if-clause takes the present simple (never will), and the result clause takes will + base verb (If it rains, we'll stay home).",
        example: 'If we miss the bus, we will be late.',
      },
    ],
  },
  questions: [
    {
      id: 'b12q01',
      levelId: 'b12',
      rule: 'zero_conditional',
      prompt: 'If you heat ice, it ___ .',
      choices: ['will melt', 'melts', 'melt', 'melted'],
      correctIndex: 1,
      choiceExplanations: [
        "'Will melt' is wrong: a general truth takes the present simple in the result clause, not 'will'.",
        "'Melts' is correct: the zero conditional uses the present simple in both clauses for a general fact.",
        "'Melt' is wrong: 'it' (singular) takes the -s form.",
        "'Melted' is wrong: the past simple does not fit a timeless fact.",
      ],
    },
    {
      id: 'b12q02',
      levelId: 'b12',
      rule: 'zero_conditional',
      prompt: 'If it rains, the ground ___ wet.',
      choices: ['get', 'gets', 'will get', 'got'],
      correctIndex: 1,
      choiceExplanations: [
        "'Get' is wrong: 'the ground' (it) takes the -s form.",
        "'Gets' is correct: a general truth uses the present simple in the result clause.",
        "'Will get' is wrong: the zero conditional states a fact, so 'will' does not fit.",
        "'Got' is wrong: the past simple does not fit a timeless fact.",
      ],
    },
    {
      id: 'b12q03',
      levelId: 'b12',
      rule: 'first_conditional',
      prompt: 'If she studies, she ___ the exam.',
      choices: ['pass', 'will pass', 'passes', 'passed'],
      correctIndex: 1,
      choiceExplanations: [
        "'Pass' is wrong: the result clause needs 'will' + base verb.",
        "'Will pass' is correct: the first conditional uses will in the result clause.",
        "'Passes' is wrong: the present simple belongs in the if-clause, not the result.",
        "'Passed' is wrong: the past simple does not fit a future possibility.",
      ],
    },
    {
      id: 'b12q04',
      levelId: 'b12',
      rule: 'first_conditional',
      prompt: 'If we miss the bus, we ___ late.',
      choices: ['are', 'will be', 'were', 'be'],
      correctIndex: 1,
      choiceExplanations: [
        "'Are' is wrong: the result clause for a future possibility needs 'will'.",
        "'Will be' is correct: the first conditional uses 'will' in the result clause.",
        "'Were' is wrong: the past simple does not fit a future possibility.",
        "'Be' is wrong: 'be' needs an auxiliary to form a future result.",
      ],
    },
    {
      id: 'b12q05',
      levelId: 'b12',
      rule: 'first_conditional',
      prompt: 'You ___ get wet if you don’t take an umbrella.',
      choices: ['would', 'do', 'will', 'did'],
      correctIndex: 2,
      choiceExplanations: [
        "'Would' is wrong: 'would' belongs to the unreal (second) conditional, not this real possibility.",
        "'Do' is wrong: 'do' is present simple and cannot form a future result.",
        "'Will' is correct: the first conditional uses 'will' + base verb in the result clause.",
        "'Did' is wrong: the past does not fit a future possibility.",
      ],
    },
    {
      id: 'b12q06',
      levelId: 'b12',
      rule: 'zero_conditional',
      prompt: 'If you ___ the button, the machine starts.',
      choices: ['press', 'pressed', 'pressing', 'will press'],
      correctIndex: 0,
      choiceExplanations: [
        "'Press' is correct: the zero conditional uses the present simple in the if-clause.",
        "'Pressed' is wrong: the past simple does not fit a general fact.",
        "'Pressing' is wrong: the -ing form cannot be the verb of the if-clause here.",
        "'Will press' is wrong: 'will' never appears in a zero-conditional if-clause.",
      ],
    },
    {
      id: 'b12q07',
      levelId: 'b12',
      rule: 'first_conditional',
      prompt: 'If it ___ tomorrow, we’ll cancel the picnic.',
      choices: ['rains', 'will rain', 'rained', 'is raining'],
      correctIndex: 0,
      choiceExplanations: [
        "'Rains' is correct: the if-clause of a first conditional takes the present simple, never 'will'.",
        "'Will rain' is wrong: 'will' is used in the result clause, not the if-clause.",
        "'Rained' is wrong: the past simple does not fit a future condition.",
        "'Is raining' is wrong: the continuous form does not fit the if-clause here.",
      ],
    },
    {
      id: 'b12q08',
      levelId: 'b12',
      rule: 'first_conditional',
      prompt: '___ you call me if you need help?',
      choices: ['Will', 'Do', 'Did', 'Are'],
      correctIndex: 0,
      choiceExplanations: [
        "'Will' is correct: a first-conditional question uses 'will' in the result clause.",
        "'Do' is wrong: the present simple cannot form a future question here.",
        "'Did' is wrong: the past does not fit a future possibility.",
        "'Are' is wrong: 'are' cannot form this question with the base verb 'call'.",
      ],
    },
    {
      id: 'b12q09',
      levelId: 'b12',
      rule: 'zero_conditional',
      prompt: 'Plants die if they ___ enough water.',
      choices: ['won’t get', 'don’t get', 'didn’t get', 'doesn’t get'],
      correctIndex: 1,
      choiceExplanations: [
        "'Won't get' is wrong: the zero conditional uses the present simple in the if-clause.",
        "'Don't get' is correct: a general fact uses the present simple, and 'they' takes 'don't'.",
        "'Didn't get' is wrong: the past does not fit a timeless fact.",
        "'Doesn't get' is wrong: 'they' is plural and takes 'don't', not 'doesn't'.",
      ],
    },
    {
      id: "b12q10",
      levelId: "b12",
      rule: "first_conditional",
      type: 'fix_sentence',
      faultySentence: "If we leave now, we will catch the film.",
      prompt: "If we leave now, we ___ the film.",
      choices: ["will catch", "catch", "caught", "catching"],
      correctIndex: 0,
      choiceExplanations: ["'will catch' is correct: the sentence requires 'will catch'.", "'catch' is wrong: the sentence requires 'will catch'.", "'caught' is wrong: the sentence requires 'will catch'.", "'catching' is wrong: the sentence requires 'will catch'."],
    },
    {
      id: "b12q11",
      levelId: "b12",
      rule: "first_conditional",
      type: 'fill_blank',
      prompt: "If it ___ tomorrow, we will cancel the picnic.",
      correctAnswer: "rains",
      acceptedAnswers: ["rains"],
      explanation: "The first conditional uses present simple in the if-clause and will in the result clause.",
    },
    {
      id: "b12q12",
      levelId: "b12",
      rule: "first_conditional",
      type: 'word_order',
      sentenceWords: ["If", "you", "study", "hard,", "you", "will", "pass."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "The first conditional uses present simple in the if-clause and will in the result clause.",
    },
  ],
};

export const basicCluster02: LevelInput[] = [
  modalLevel,
  articlesLevel,
  comparativesLevel,
  pastPerfectLevel,
  prepositionsTimeLevel,
  conditionalsLevel,
];
