/**
 * Basic track content cluster. Keep this module data-only so each cluster can
 * be authored and reviewed independently.
 */

import type { LevelInput } from '../../types';

const presentSimpleLevel: LevelInput = {
  id: 'b01',
  trackId: 'basic',
  number: 1,
  title: 'Present Simple',
  topic: {
    title: 'Present Simple',
    summary:
      'The present simple describes habits, routines, and facts that are generally true. With he, she, and it, the verb adds -s.',
    rules: [
      {
        rule: 'present_simple_form',
        title: 'Form: he/she/it + verb-s',
        explanation:
          "Use the base verb for I/you/we/they (I work) and add -s (or -es) for he/she/it (she works). Negatives use do not/don't or does not/doesn't + the base verb; questions use do/does + subject + base verb.",
        example: 'She works in a hospital. / Do you like coffee?',
      },
      {
        rule: 'present_simple_usage',
        title: 'Use: habits, routines, and facts',
        explanation:
          'Use the present simple for repeated actions and routines (I drink tea every morning), general facts (Water boils at 100 °C), and fixed schedules (The bus leaves at six).',
        example: 'He plays tennis on Sundays.',
      },
    ],
  },
  questions: [
    {
      id: 'b01q01',
      levelId: 'b01',
      rule: 'present_simple_form',
      prompt: 'My sister ___ in a bank.',
      choices: ['works', 'work', 'working', 'is work'],
      correctIndex: 0,
      choiceExplanations: [
        "'Works' is correct: with 'my sister' (she), the present-simple verb takes -s.",
        "'Work' is wrong: the base form is used for I/you/we/they, not for she.",
        "'Working' is wrong: the -ing form needs a helper verb (is working), and this is a routine, not an action happening now.",
        "'Is work' is wrong: 'is' is never followed by the base verb.",
      ],
    },
    {
      id: 'b01q02',
      levelId: 'b01',
      rule: 'present_simple_form',
      prompt: 'They ___ English every day.',
      choices: ['studies', 'study', 'is studying', 'studying'],
      correctIndex: 1,
      choiceExplanations: [
        "'Studies' is wrong: -s is added only for he/she/it, and 'they' takes the base form.",
        "'Study' is correct: 'they' takes the base verb in the present simple.",
        "'Is studying' is wrong: present continuous fits an action happening now, not a daily habit.",
        "'Studying' is wrong: the -ing form cannot stand alone as the main verb.",
      ],
    },
    {
      id: 'b01q03',
      levelId: 'b01',
      rule: 'present_simple_form',
      prompt: 'He ___ his car to work.',
      choices: ['drive', 'is driving', 'drives', 'driving'],
      correctIndex: 2,
      choiceExplanations: [
        "'Drive' is wrong: the base form is for I/you/we/they, not for he.",
        "'Is driving' is wrong: it describes an action in progress now, not a regular habit.",
        "'Drives' is correct: with 'he', the present-simple verb adds -s.",
        "'Driving' is wrong: the -ing form needs a helper verb to be a main verb.",
      ],
    },
    {
      id: 'b01q04',
      levelId: 'b01',
      rule: 'present_simple_form',
      prompt: '___ you like pizza?',
      choices: ['Does', 'Is', 'Are', 'Do'],
      correctIndex: 3,
      choiceExplanations: [
        "'Does' is wrong: 'does' is used with he/she/it, and the subject here is 'you'.",
        "'Is' is wrong: questions with 'like' need the auxiliary do/does, not the verb 'to be'.",
        "'Are' is wrong: 'are' is the verb 'to be' and cannot form a question with 'like'.",
        "'Do' is correct: 'you' takes the auxiliary 'do' in present-simple questions.",
      ],
    },
    {
      id: 'b01q05',
      levelId: 'b01',
      rule: 'present_simple_form',
      prompt: 'She ___ TV in the evening.',
      choices: ['watch', 'watches', 'is watching', 'watching'],
      correctIndex: 1,
      choiceExplanations: [
        "'Watch' is wrong: the base form is for I/you/we/they, not for she.",
        "'Watches' is correct: after -ch, she adds -es in the present simple.",
        "'Is watching' is wrong: present continuous is for an action happening now, not an evening habit.",
        "'Watching' is wrong: the -ing form cannot be the main verb alone.",
      ],
    },
    {
      id: 'b01q06',
      levelId: 'b01',
      rule: 'present_simple_form',
      prompt: 'The shop ___ its doors at nine o’clock.',
      choices: ['opens', 'open', 'is open', 'opening'],
      correctIndex: 0,
      choiceExplanations: [
        "'Opens' is correct: 'the shop' (it) takes the -s form in the present simple.",
        "'Open' is wrong: the base form is for I/you/we/they, not for it.",
        "'Is open' is wrong: 'is open' is a state and cannot take an object like 'its doors'.",
        "'Opening' is wrong: the -ing form needs a helper verb and does not fit a schedule fact.",
      ],
    },
    {
      id: 'b01q07',
      levelId: 'b01',
      rule: 'present_simple_usage',
      prompt: 'Water ___ at 100 degrees Celsius.',
      choices: ['boil', 'is boiling', 'boils', 'boiled'],
      correctIndex: 2,
      choiceExplanations: [
        "'Boil' is wrong: a general fact uses the -s form because water is a singular subject (it).",
        "'Is boiling' is wrong: present continuous is for an action happening now, not a general truth.",
        "'Boils' is correct: the present simple states a general fact.",
        "'Boiled' is wrong: past simple describes a finished past event, not a timeless fact.",
      ],
    },
    {
      id: 'b01q08',
      levelId: 'b01',
      rule: 'present_simple_usage',
      prompt: 'We ___ to the gym every morning.',
      choices: ['goes', 'going', 'go', 'are go'],
      correctIndex: 2,
      choiceExplanations: [
        "'Goes' is wrong: -es is for he/she/it; the subject is 'we'.",
        "'Going' is wrong: the -ing form cannot be the main verb alone here.",
        "'Go' is correct: a daily routine with 'we' takes the base form.",
        "'Are go' is wrong: 'are' is never followed by the base verb.",
      ],
    },
    {
      id: 'b01q09',
      levelId: 'b01',
      rule: 'present_simple_usage',
      prompt: 'He ___ football on Saturdays.',
      choices: ['is playing', 'play', 'plays', 'playing'],
      correctIndex: 2,
      choiceExplanations: [
        "'Is playing' is wrong: that describes right now, but Saturdays is a repeated habit.",
        "'Play' is wrong: the base form is for I/you/we/they, not for he.",
        "'Plays' is correct: the present simple describes a habit on Saturdays.",
        "'Playing' is wrong: the -ing form cannot be the main verb alone.",
      ],
    },
    {
      id: "b01q10",
      levelId: "b01",
      rule: "present_simple_form",
      type: 'fix_sentence',
      faultySentence: "The train leaves at six every day.",
      prompt: "The train ___ at six every day.",
      choices: ["leaves", "leave", "is leaving", "left"],
      correctIndex: 0,
      choiceExplanations: ["'leaves' is correct: the sentence requires 'leaves'.", "'leave' is wrong: the sentence requires 'leaves'.", "'is leaving' is wrong: the sentence requires 'leaves'.", "'left' is wrong: the sentence requires 'leaves'."],
    },
    {
      id: "b01q11",
      levelId: "b01",
      rule: "present_simple_usage",
      type: 'fill_blank',
      prompt: "I ___ coffee every morning.",
      correctAnswer: "drink",
      acceptedAnswers: ["drink"],
      explanation: "General habits use the present simple; plural subjects take the base verb.",
    },
    {
      id: "b01q12",
      levelId: "b01",
      rule: "present_simple_usage",
      type: 'word_order',
      sentenceWords: ["Cats", "like", "milk."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "General habits use the present simple; plural subjects take the base verb.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 2 — Present Continuous
// ─────────────────────────────────────────────────────────────────────────────

const presentContinuousLevel: LevelInput = {
  id: 'b02',
  trackId: 'basic',
  number: 2,
  title: 'Present Continuous',
  topic: {
    title: 'Present Continuous',
    summary:
      'The present continuous describes an action happening now or around now, and temporary situations. It is formed with am/is/are + verb-ing.',
    rules: [
      {
        rule: 'present_continuous_form',
        title: 'Form: am/is/are + verb-ing',
        explanation:
          "Formed with am/is/are + the -ing form of the verb (I am working, she is working, we are working). Negatives add not (isn't/aren't); questions put am/is/are before the subject.",
        example: 'They are watching a film right now.',
      },
      {
        rule: 'present_simple_vs_continuous',
        title: 'Present Simple vs Present Continuous',
        explanation:
          'Use the present continuous for actions in progress now or temporary situations; use the present simple for habits and permanent facts. A word like "now" or "today" points to continuous; "every day" points to simple.',
        example: 'She is working today, but she works at a clinic every week.',
      },
    ],
  },
  questions: [
    {
      id: 'b02q01',
      levelId: 'b02',
      rule: 'present_continuous_form',
      prompt: 'Listen! The baby ___ .',
      choices: ['cries', 'is crying', 'cry', 'crying'],
      correctIndex: 1,
      choiceExplanations: [
        "'Cries' is wrong: the present simple fits a habit, not the action happening right now that 'Listen!' points to.",
        "'Is crying' is correct: present continuous (is + crying) describes the action happening now.",
        "'Cry' is wrong: the base form needs the right subject and does not fit an action in progress.",
        "'Crying' is wrong: the -ing form must be paired with am/is/are.",
      ],
    },
    {
      id: 'b02q02',
      levelId: 'b02',
      rule: 'present_continuous_form',
      prompt: 'We ___ lunch right now.',
      choices: ['have', 'is having', 'having', 'are having'],
      correctIndex: 3,
      choiceExplanations: [
        "'Have' is wrong: the present simple would describe a habit, not what is happening at this moment.",
        "'Is having' is wrong: 'is' goes with he/she/it, not 'we'.",
        "'Having' is wrong: the -ing form needs am/is/are.",
        "'Are having' is correct: 'we' takes 'are' + the -ing form for an action happening now.",
      ],
    },
    {
      id: 'b02q03',
      levelId: 'b02',
      rule: 'present_continuous_form',
      prompt: 'She ___ a book at the moment.',
      choices: ['reads', 'is reading', 'read', 'is read'],
      correctIndex: 1,
      choiceExplanations: [
        "'Reads' is wrong: the present simple describes a habit; 'at the moment' signals an action in progress now.",
        "'Is reading' is correct: present continuous (is + reading) fits 'at the moment'.",
        "'Read' is wrong: the base form does not fit a singular subject doing something now.",
        "'Is read' is wrong: that is passive voice, but the book is being read, not reading itself.",
      ],
    },
    {
      id: 'b02q04',
      levelId: 'b02',
      rule: 'present_continuous_form',
      prompt: '___ they coming to the party?',
      choices: ['Does', 'Is', 'Are', 'Do'],
      correctIndex: 2,
      choiceExplanations: [
        "'Does' is wrong: 'does' makes a present-simple question, and the verb here is 'coming', not a base form.",
        "'Is' is wrong: 'is' goes with he/she/it, not 'they'.",
        "'Are' is correct: 'they' takes 'are' before the -ing form in a present-continuous question.",
        "'Do' is wrong: 'do' cannot precede 'coming'; a present-continuous question needs am/is/are.",
      ],
    },
    {
      id: 'b02q05',
      levelId: 'b02',
      rule: 'present_continuous_form',
      prompt: 'He ___ for the bus now.',
      choices: ['waits', 'is waiting', 'wait', 'is wait'],
      correctIndex: 1,
      choiceExplanations: [
        "'Waits' is wrong: the present simple describes a habit; 'now' signals an action in progress.",
        "'Is waiting' is correct: present continuous (is + waiting) fits the action happening now.",
        "'Wait' is wrong: the base form does not fit a singular subject in an ongoing action.",
        "'Is wait' is wrong: 'is' must be followed by the -ing form, not the base verb.",
      ],
    },
    {
      id: 'b02q06',
      levelId: 'b02',
      rule: 'present_simple_vs_continuous',
      prompt: 'I usually ___ tea, but today I ___ coffee.',
      choices: ['am drinking / drink', 'drink / am drinking', 'drink / drink', 'am drinking / am drinking'],
      correctIndex: 1,
      choiceExplanations: [
        "'Am drinking / drink' is wrong: the usual habit takes the present simple, and the exception today takes the continuous.",
        "'Drink / am drinking' is correct: 'usually' signals the habit (present simple), and 'today' signals the temporary change (present continuous).",
        "'Drink / drink' is wrong: the second verb ignores 'today', which points to a temporary action.",
        "'Am drinking / am drinking' is wrong: the first verb is a usual habit and should be present simple.",
      ],
    },
    {
      id: 'b02q07',
      levelId: 'b02',
      rule: 'present_simple_vs_continuous',
      prompt: 'Look! It ___ outside.',
      choices: ['snows', 'snow', 'is snowing', 'snowing'],
      correctIndex: 2,
      choiceExplanations: [
        "'Snows' is wrong: 'Look!' points to what is happening right now, so the present simple is wrong.",
        "'Snow' is wrong: the base form does not fit a singular subject in an action in progress.",
        "'Is snowing' is correct: 'Look!' signals an action happening at this moment.",
        "'Snowing' is wrong: the -ing form needs am/is/are.",
      ],
    },
    {
      id: 'b02q08',
      levelId: 'b02',
      rule: 'present_simple_vs_continuous',
      prompt: 'She ___ in London now, but she ___ in Paris every summer.',
      choices: ['lives / is staying', 'is living / stays', 'is living / is staying', 'lives / stays'],
      correctIndex: 1,
      choiceExplanations: [
        "'Lives / is staying' is wrong: a permanent residence takes the present simple, not the continuous.",
        "'Is living / stays' is correct: the temporary situation now takes the continuous, and the yearly habit takes the simple.",
        "'Is living / is staying' is wrong: 'every summer' is a habit and needs the present simple.",
        "'Lives / stays' is wrong: the first verb ignores 'now', which signals a temporary situation.",
      ],
    },
    {
      id: 'b02q09',
      levelId: 'b02',
      rule: 'present_simple_vs_continuous',
      prompt: 'Every day he ___ to school, but today he ___ the bus.',
      choices: ['is walking / takes', 'walks / is taking', 'walks / takes', 'is walking / is taking'],
      correctIndex: 1,
      choiceExplanations: [
        "'Is walking / takes' is wrong: 'every day' is a habit and needs the present simple.",
        "'Walks / is taking' is correct: the daily habit takes the present simple, and today's exception takes the present continuous.",
        "'Walks / takes' is wrong: the second verb ignores 'today', which signals a change from the routine.",
        "'Is walking / is taking' is wrong: the first verb ignores 'every day', which signals a habit.",
      ],
    },
    {
      id: "b02q10",
      levelId: "b02",
      rule: "present_simple_vs_continuous",
      type: 'fix_sentence',
      faultySentence: "She walks to work every day.",
      prompt: "She ___ to work every day, but today she is cycling.",
      choices: ["walks", "is walking", "walk", "walked"],
      correctIndex: 0,
      choiceExplanations: ["'walks' is correct: the sentence requires 'walks'.", "'is walking' is wrong: the sentence requires 'walks'.", "'walk' is wrong: the sentence requires 'walks'.", "'walked' is wrong: the sentence requires 'walks'."],
    },
    {
      id: "b02q11",
      levelId: "b02",
      rule: "present_simple_vs_continuous",
      type: 'fill_blank',
      prompt: "They ___ dinner right now.",
      correctAnswer: "are having",
      acceptedAnswers: ["are having", "have"],
      explanation: "Use the present continuous for an action happening now.",
    },
    {
      id: "b02q12",
      levelId: "b02",
      rule: "present_simple_vs_continuous",
      type: 'word_order',
      sentenceWords: ["We", "are", "watching", "a", "film."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "Use the present continuous for an action happening now.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 3 — Past Simple
// ─────────────────────────────────────────────────────────────────────────────

const pastSimpleLevel: LevelInput = {
  id: 'b03',
  trackId: 'basic',
  number: 3,
  title: 'Past Simple',
  topic: {
    title: 'Past Simple',
    summary:
      'The past simple describes finished actions and events in the past. Regular verbs add -ed; many common verbs are irregular.',
    rules: [
      {
        rule: 'past_simple_form',
        title: 'Form: regular -ed and irregular verbs',
        explanation:
          "Regular verbs add -ed (work → worked). Irregular verbs change form (go → went, see → saw, eat → ate). The form is the same for all subjects, and negatives/questions use did + the base verb (He didn't go; Did you see her?).",
        example: 'I visited Rome last year. / She went home early.',
      },
      {
        rule: 'past_simple_usage',
        title: 'Use: finished actions with past time markers',
        explanation:
          'Use the past simple for actions and states that finished at a specific time in the past, often with markers like yesterday, last week, ago, or in 2010. The action is complete and has no connection to now.',
        example: 'We watched a film yesterday evening.',
      },
    ],
  },
  questions: [
    {
      id: 'b03q01',
      levelId: 'b03',
      rule: 'past_simple_form',
      prompt: 'She ___ to the meeting yesterday.',
      choices: ['go', 'went', 'goes', 'gone'],
      correctIndex: 1,
      choiceExplanations: [
        "'Go' is wrong: the base form is not used for a finished past event.",
        "'Went' is correct: 'went' is the irregular past-simple form of 'go'.",
        "'Goes' is wrong: the present simple describes a habit, but 'yesterday' signals the past.",
        "'Gone' is wrong: 'gone' is the past participle and needs a helper verb (has gone / had gone).",
      ],
    },
    {
      id: 'b03q02',
      levelId: 'b03',
      rule: 'past_simple_form',
      prompt: 'They ___ the museum last weekend.',
      choices: ['visit', 'visits', 'visited', 'visiting'],
      correctIndex: 2,
      choiceExplanations: [
        "'Visit' is wrong: the base form does not express a finished past action.",
        "'Visits' is wrong: the -s form is present simple for he/she/it, not past.",
        "'Visited' is correct: regular verbs add -ed for the past simple.",
        "'Visiting' is wrong: the -ing form needs a helper verb and does not fit a finished event.",
      ],
    },
    {
      id: 'b03q03',
      levelId: 'b03',
      rule: 'past_simple_form',
      prompt: 'I ___ a strange noise last night.',
      choices: ['hear', 'hears', 'am hearing', 'heard'],
      correctIndex: 3,
      choiceExplanations: [
        "'Hear' is wrong: the base form does not express a finished past action.",
        "'Hears' is wrong: present simple -s form, but the event is in the past.",
        "'Am hearing' is wrong: present continuous describes now, not last night.",
        "'Heard' is correct: 'heard' is the irregular past-simple form of 'hear'.",
      ],
    },
    {
      id: 'b03q04',
      levelId: 'b03',
      rule: 'past_simple_form',
      prompt: '___ you call her yesterday?',
      choices: ['Do', 'Did', 'Does', 'Have'],
      correctIndex: 1,
      choiceExplanations: [
        "'Do' is wrong: 'do' is present; 'yesterday' signals a past question.",
        "'Did' is correct: past-simple questions use 'did' + the base verb.",
        "'Does' is wrong: 'does' is present simple and is for he/she/it.",
        "'Have' is wrong: 'have' would make a present-perfect question, which does not take a past time marker like 'yesterday'.",
      ],
    },
    {
      id: 'b03q05',
      levelId: 'b03',
      rule: 'past_simple_form',
      prompt: 'He didn’t ___ the email.',
      choices: ['sent', 'send', 'sends', 'sending'],
      correctIndex: 1,
      choiceExplanations: [
        "'Sent' is wrong: after 'didn't', the verb returns to the base form.",
        "'Send' is correct: negatives with 'didn't' take the base verb, whatever the tense of the main verb.",
        "'Sends' is wrong: 'sends' is present simple and never follows 'didn't'.",
        "'Sending' is wrong: the -ing form cannot follow 'didn't'.",
      ],
    },
    {
      id: 'b03q06',
      levelId: 'b03',
      rule: 'past_simple_form',
      prompt: 'They ___ dinner at eight o’clock last night.',
      choices: ['eat', 'eats', 'ate', 'eaten'],
      correctIndex: 2,
      choiceExplanations: [
        "'Eat' is wrong: the base form does not express a finished past action.",
        "'Eats' is wrong: present simple for he/she/it, but the dinner was last night.",
        "'Ate' is correct: 'ate' is the irregular past-simple form of 'eat'.",
        "'Eaten' is wrong: 'eaten' is the past participle and needs a helper verb (has eaten / had eaten).",
      ],
    },
    {
      id: 'b03q07',
      levelId: 'b03',
      rule: 'past_simple_usage',
      prompt: 'We ___ to Spain two years ago.',
      choices: ['travelled', 'travel', 'travels', 'are travelling'],
      correctIndex: 0,
      choiceExplanations: [
        "'Travelled' is correct: 'ago' marks a finished past time, so the past simple fits.",
        "'Travel' is wrong: the base form does not fit a finished past trip.",
        "'Travels' is wrong: present simple for he/she/it, and the trip was two years ago.",
        "'Are travelling' is wrong: present continuous describes now, not two years ago.",
      ],
    },
    {
      id: 'b03q08',
      levelId: 'b03',
      rule: 'past_simple_usage',
      prompt: 'The concert ___ at nine last night.',
      choices: ['starts', 'started', 'is starting', 'starting'],
      correctIndex: 1,
      choiceExplanations: [
        "'Starts' is wrong: present simple fits a schedule, but the concert was last night.",
        "'Started' is correct: 'last night' marks a finished past event.",
        "'Is starting' is wrong: present continuous describes now, not a past event.",
        "'Starting' is wrong: the -ing form needs a helper verb.",
      ],
    },
    {
      id: 'b03q09',
      levelId: 'b03',
      rule: 'past_simple_usage',
      prompt: 'I ___ my keys this morning.',
      choices: ['lose', 'am losing', 'lost', 'losing'],
      correctIndex: 2,
      choiceExplanations: [
        "'Lose' is wrong: the base form does not express a finished past action.",
        "'Am losing' is wrong: present continuous describes a process now, not an event this morning.",
        "'Lost' is correct: 'this morning' is a past time, so the past simple fits.",
        "'Losing' is wrong: the -ing form needs a helper verb.",
      ],
    },
    {
      id: "b03q10",
      levelId: "b03",
      rule: "past_simple_usage",
      type: 'fix_sentence',
      faultySentence: "When did you move here?",
      prompt: "When ___ you move here?",
      choices: ["did", "do", "does", "are"],
      correctIndex: 0,
      choiceExplanations: ["'did' is correct: the sentence requires 'did'.", "'do' is wrong: the sentence requires 'did'.", "'does' is wrong: the sentence requires 'did'.", "'are' is wrong: the sentence requires 'did'."],
    },
    {
      id: "b03q11",
      levelId: "b03",
      rule: "past_simple_usage",
      type: 'fill_blank',
      prompt: "I ___ my keys this morning.",
      correctAnswer: "lost",
      acceptedAnswers: ["lost"],
      explanation: "The past simple describes a completed action at a finished past time.",
    },
    {
      id: "b03q12",
      levelId: "b03",
      rule: "past_simple_usage",
      type: 'word_order',
      sentenceWords: ["She", "visited", "the", "museum", "yesterday."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "The past simple describes a completed action at a finished past time.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 4 — Past Continuous
// ─────────────────────────────────────────────────────────────────────────────

const pastContinuousLevel: LevelInput = {
  id: 'b04',
  trackId: 'basic',
  number: 4,
  title: 'Past Continuous',
  topic: {
    title: 'Past Continuous',
    summary:
      'The past continuous describes an action that was in progress at a moment in the past, often interrupted by a shorter past-simple action.',
    rules: [
      {
        rule: 'past_continuous_form',
        title: 'Form: was/were + verb-ing',
        explanation:
          "Formed with was (I/he/she/it) or were (you/we/they) + the -ing form of the verb. It sets the background action in the past (I was reading).",
        example: 'They were playing football at five o’clock.',
      },
      {
        rule: 'past_simple_vs_continuous',
        title: 'Past Continuous vs Past Simple',
        explanation:
          'Use the past continuous for the longer background action in progress, and the past simple for the shorter action that interrupts it (While I was cooking, the phone rang). "When" often joins the interrupting action to the background one.',
        example: 'I was driving home when it started to rain.',
      },
    ],
  },
  questions: [
    {
      id: 'b04q01',
      levelId: 'b04',
      rule: 'past_continuous_form',
      prompt: 'At nine last night, we ___ dinner.',
      choices: ['had', 'were having', 'are having', 'having'],
      correctIndex: 1,
      choiceExplanations: [
        "'Had' is wrong: the past simple is a finished event; 'at nine last night' sets a moment in progress.",
        "'Were having' is correct: past continuous (were + having) describes an action in progress at a past moment.",
        "'Are having' is wrong: that is present continuous, but the moment was last night.",
        "'Having' is wrong: the -ing form needs was/were.",
      ],
    },
    {
      id: 'b04q02',
      levelId: 'b04',
      rule: 'past_continuous_form',
      prompt: 'I ___ TV when the lights went out.',
      choices: ['watched', 'am watching', 'was watching', 'watching'],
      correctIndex: 2,
      choiceExplanations: [
        "'Watched' is wrong: the past simple would make watching a finished event, but the watching was in progress when something happened.",
        "'Am watching' is wrong: present continuous describes now, not the past.",
        "'Was watching' is correct: past continuous (was + watching) sets the action in progress in the past.",
        "'Watching' is wrong: the -ing form needs a helper verb.",
      ],
    },
    {
      id: 'b04q03',
      levelId: 'b04',
      rule: 'past_continuous_form',
      prompt: 'They ___ football at five o’clock yesterday.',
      choices: ['played', 'are playing', 'play', 'were playing'],
      correctIndex: 3,
      choiceExplanations: [
        "'Played' is wrong: the past simple is a finished event, not an action in progress at a set time.",
        "'Are playing' is wrong: present continuous describes now, not yesterday.",
        "'Play' is wrong: the present simple does not fit a past time.",
        "'Were playing' is correct: 'at five o'clock yesterday' is a past moment, and past continuous shows the action in progress then.",
      ],
    },
    {
      id: 'b04q04',
      levelId: 'b04',
      rule: 'past_continuous_form',
      prompt: 'She ___ to music when I called.',
      choices: ['listened', 'was listening', 'is listening', 'listening'],
      correctIndex: 1,
      choiceExplanations: [
        "'Listened' is wrong: the past simple is a finished event, but the listening was in progress when I called.",
        "'Was listening' is correct: past continuous (was + listening) sets the action in progress at the moment of the call.",
        "'Is listening' is wrong: present continuous describes now, not the past.",
        "'Listening' is wrong: the -ing form needs a helper verb.",
      ],
    },
    {
      id: 'b04q05',
      levelId: 'b04',
      rule: 'past_continuous_form',
      prompt: 'We ___ home when the storm began.',
      choices: ['drive', 'were driving', 'drove', 'are driving'],
      correctIndex: 1,
      choiceExplanations: [
        "'Drive' is wrong: the base form does not fit a past action.",
        "'Were driving' is correct: past continuous (were + driving) describes the action in progress when the storm began.",
        "'Drove' is wrong: the past simple would present the driving as finished, not as background to the storm.",
        "'Are driving' is wrong: present continuous describes now, not the past.",
      ],
    },
    {
      id: 'b04q06',
      levelId: 'b04',
      rule: 'past_simple_vs_continuous',
      prompt: 'While I ___ , the phone rang.',
      choices: ['cooked', 'was cooking', 'cook', 'am cooking'],
      correctIndex: 1,
      choiceExplanations: [
        "'Cooked' is wrong: 'while' sets a longer action in progress, which needs the past continuous.",
        "'Was cooking' is correct: 'while' + past continuous sets the background action; the phone rang during it.",
        "'Cook' is wrong: the present simple does not fit a past action.",
        "'Am cooking' is wrong: present continuous describes now, not the past.",
      ],
    },
    {
      id: 'b04q07',
      levelId: 'b04',
      rule: 'past_simple_vs_continuous',
      prompt: 'When the teacher arrived, the students ___ .',
      choices: ['talked', 'were talking', 'are talking', 'talk'],
      correctIndex: 1,
      choiceExplanations: [
        "'Talked' is wrong: the past simple would make the talking finished before the teacher arrived, but it was still in progress.",
        "'Were talking' is correct: the students were in the middle of talking when the teacher arrived.",
        "'Are talking' is wrong: present continuous describes now, not the past.",
        "'Talk' is wrong: the present simple does not fit a past scene.",
      ],
    },
    {
      id: 'b04q08',
      levelId: 'b04',
      rule: 'past_simple_vs_continuous',
      prompt: 'It ___ when we left the house.',
      choices: ['rained', 'rains', 'was raining', 'is raining'],
      correctIndex: 2,
      choiceExplanations: [
        "'Rained' is wrong: the past simple presents the rain as a finished event, not as ongoing when we left.",
        "'Rains' is wrong: the present simple does not fit a past scene.",
        "'Was raining' is correct: the rain was in progress at the moment we left.",
        "'Is raining' is wrong: present continuous describes now, not the past.",
      ],
    },
    {
      id: 'b04q09',
      levelId: 'b04',
      rule: 'past_simple_vs_continuous',
      prompt: 'I ___ down the street when I saw an old friend.',
      choices: ['walk', 'was walking', 'walked', 'am walking'],
      correctIndex: 1,
      choiceExplanations: [
        "'Walk' is wrong: the base form does not fit a past action.",
        "'Was walking' is correct: past continuous sets the action in progress when the seeing happened.",
        "'Walked' is wrong: the past simple would present the walking as finished, but it was the background to seeing my friend.",
        "'Am walking' is wrong: present continuous describes now, not the past.",
      ],
    },
    {
      id: "b04q10",
      levelId: "b04",
      rule: "past_simple_vs_continuous",
      type: 'fix_sentence',
      faultySentence: "They were playing chess when I came in.",
      prompt: "They ___ chess when I came in.",
      choices: ["were playing", "played", "are playing", "play"],
      correctIndex: 0,
      choiceExplanations: ["'were playing' is correct: the sentence requires 'were playing'.", "'played' is wrong: the sentence requires 'were playing'.", "'are playing' is wrong: the sentence requires 'were playing'.", "'play' is wrong: the sentence requires 'were playing'."],
    },
    {
      id: "b04q11",
      levelId: "b04",
      rule: "past_simple_vs_continuous",
      type: 'fill_blank',
      prompt: "I ___ down the street when it started to rain.",
      correctAnswer: "was walking",
      acceptedAnswers: ["was walking"],
      explanation: "Use the past continuous for an action in progress when another past event happened.",
    },
    {
      id: "b04q12",
      levelId: "b04",
      rule: "past_simple_vs_continuous",
      type: 'word_order',
      sentenceWords: ["We", "were", "eating", "when", "she", "called."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "Use the past continuous for an action in progress when another past event happened.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 5 — Present Perfect
// ─────────────────────────────────────────────────────────────────────────────

const presentPerfectLevel: LevelInput = {
  id: 'b05',
  trackId: 'basic',
  number: 5,
  title: 'Present Perfect',
  topic: {
    title: 'Present Perfect',
    summary:
      'The present perfect links the past to now: an action at an unspecified past time, a change, or an experience, whose result still matters. It is formed with has/have + the past participle.',
    rules: [
      {
        rule: 'present_perfect_form',
        title: 'Form: has/have + past participle',
        explanation:
          "Formed with has (he/she/it) or have (I/you/we/they) + the past participle (worked, gone, seen). Negatives add not (hasn't/haven't); questions put has/have before the subject. Words like just, already, yet, ever, never, and since often go with it.",
        example: 'She has already finished. / Have you ever been to Spain?',
      },
      {
        rule: 'present_perfect_vs_past_simple',
        title: 'Present Perfect vs Past Simple',
        explanation:
          'Use the present perfect when the exact time is not stated or when the result matters now (I have lost my keys — I cannot find them). Use the past simple when the time is finished and specific (I lost my keys yesterday).',
        example: 'He has visited Rome (experience). / He visited Rome in 2019 (specific past time).',
      },
    ],
  },
  questions: [
    {
      id: 'b05q01',
      levelId: 'b05',
      rule: 'present_perfect_form',
      prompt: 'She ___ her homework already.',
      choices: ['finished', 'has finished', 'is finishing', 'finishes'],
      correctIndex: 1,
      choiceExplanations: [
        "'Finished' is wrong: without a specific past time, the finished action that matters now needs the present perfect.",
        "'Has finished' is correct: 'already' signals the present perfect, and 'she' takes 'has'.",
        "'Is finishing' is wrong: present continuous means the action is still in progress.",
        "'Finishes' is wrong: the present simple describes a habit, not a completed action.",
      ],
    },
    {
      id: 'b05q02',
      levelId: 'b05',
      rule: 'present_perfect_form',
      prompt: 'We ___ this film twice.',
      choices: ['see', 'have seen', 'saw', 'are seeing'],
      correctIndex: 1,
      choiceExplanations: [
        "'See' is wrong: the base form does not express a completed experience.",
        "'Have seen' is correct: 'we' takes 'have' + the past participle for an experience up to now.",
        "'Saw' is wrong: the past simple needs a specific past time, which is not given here.",
        "'Are seeing' is wrong: present continuous describes the action happening now.",
      ],
    },
    {
      id: 'b05q03',
      levelId: 'b05',
      rule: 'present_perfect_form',
      prompt: 'I ___ never been to Japan.',
      choices: ['have', 'has', 'am', 'did'],
      correctIndex: 0,
      choiceExplanations: [
        "'Have' is correct: 'I' takes 'have' + the past participle in the present perfect.",
        "'Has' is wrong: 'has' is used with he/she/it, not with 'I'.",
        "'Am' is wrong: 'am' would start a present-continuous form, but 'been' needs 'have'.",
        "'Did' is wrong: 'did' makes a past-simple question and cannot precede 'been'.",
      ],
    },
    {
      id: 'b05q04',
      levelId: 'b05',
      rule: 'present_perfect_form',
      prompt: '___ you ever eaten sushi?',
      choices: ['Did', 'Have', 'Do', 'Are'],
      correctIndex: 1,
      choiceExplanations: [
        "'Did' is wrong: 'did' makes a past-simple question and does not go with the participle 'eaten'.",
        "'Have' is correct: present-perfect questions about experience use 'have' + past participle.",
        "'Do' is wrong: 'do' cannot precede the participle 'eaten'.",
        "'Are' is wrong: 'are' would need an -ing form, not 'eaten'.",
      ],
    },
    {
      id: 'b05q05',
      levelId: 'b05',
      rule: 'present_perfect_form',
      prompt: 'He ___ just left.',
      choices: ['has', 'have', 'is', 'did'],
      correctIndex: 0,
      choiceExplanations: [
        "'Has' is correct: 'he' takes 'has' with the participle 'left', and 'just' signals a very recent event.",
        "'Have' is wrong: 'have' is used with I/you/we/they, not with he.",
        "'Is' is wrong: 'is' would make a continuous form, but 'left' is a participle.",
        "'Did' is wrong: 'did' makes a past-simple form and does not go with 'just left'.",
      ],
    },
    {
      id: 'b05q06',
      levelId: 'b05',
      rule: 'present_perfect_form',
      prompt: 'They haven’t ___ the report yet.',
      choices: ['wrote', 'write', 'written', 'writing'],
      correctIndex: 2,
      choiceExplanations: [
        "'Wrote' is wrong: 'wrote' is the past simple form and does not follow 'haven't'.",
        "'Write' is wrong: after 'haven't', the main verb must be the past participle.",
        "'Written' is correct: 'haven't' + the past participle 'written' forms the present perfect.",
        "'Writing' is wrong: the -ing form does not follow 'haven't'.",
      ],
    },
    {
      id: 'b05q07',
      levelId: 'b05',
      rule: 'present_perfect_vs_past_simple',
      prompt: 'I ___ my keys. I can’t find them anywhere.',
      choices: ['lost', 'have lost', 'lose', 'am losing'],
      correctIndex: 1,
      choiceExplanations: [
        "'Lost' is wrong: the past simple would need a specific past time, and here the result matters now.",
        "'Have lost' is correct: the loss happened in the past and its result (I can't find them) matters now.",
        "'Lose' is wrong: the present simple does not fit a finished past event.",
        "'Am losing' is wrong: present continuous means I am losing them right now, which is not the meaning.",
      ],
    },
    {
      id: 'b05q08',
      levelId: 'b05',
      rule: 'present_perfect_vs_past_simple',
      prompt: 'She ___ Paris in 2019.',
      choices: ['has visited', 'visits', 'visited', 'is visiting'],
      correctIndex: 2,
      choiceExplanations: [
        "'Has visited' is wrong: 'in 2019' is a finished, specific past time, which belongs with the past simple.",
        "'Visits' is wrong: the present simple does not fit a past event.",
        "'Visited' is correct: a specific finished time ('in 2019') takes the past simple.",
        "'Is visiting' is wrong: present continuous describes the visit happening now.",
      ],
    },
    {
      id: 'b05q09',
      levelId: 'b05',
      rule: 'present_perfect_vs_past_simple',
      prompt: 'We ___ here since 2020.',
      choices: ['lived', 'have lived', 'live', 'are living'],
      correctIndex: 1,
      choiceExplanations: [
        "'Lived' is wrong: the past simple would make the living finished, but it continues to now.",
        "'Have lived' is correct: 'since 2020' connects the past to the present, so the present perfect fits.",
        "'Live' is wrong: the present simple cannot express a period that began in the past.",
        "'Are living' is wrong: present continuous describes now, not a period from 2020.",
      ],
    },
    {
      id: "b05q10",
      levelId: "b05",
      rule: "present_perfect_vs_past_simple",
      type: 'fix_sentence',
      faultySentence: "He has broken his leg.",
      prompt: "He ___ his leg, so he cannot play today.",
      choices: ["has broken", "broke", "breaks", "is breaking"],
      correctIndex: 0,
      choiceExplanations: ["'has broken' is correct: the sentence requires 'has broken'.", "'broke' is wrong: the sentence requires 'has broken'.", "'breaks' is wrong: the sentence requires 'has broken'.", "'is breaking' is wrong: the sentence requires 'has broken'."],
    },
    {
      id: "b05q11",
      levelId: "b05",
      rule: "present_perfect_vs_past_simple",
      type: 'fill_blank',
      prompt: "We ___ here since 2020.",
      correctAnswer: "have lived",
      acceptedAnswers: ["have lived", "lived"],
      explanation: "Use the present perfect when a past event has a result or connection to now.",
    },
    {
      id: "b05q12",
      levelId: "b05",
      rule: "present_perfect_vs_past_simple",
      type: 'word_order',
      sentenceWords: ["She", "has", "finished", "her", "homework."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "Use the present perfect when a past event has a result or connection to now.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 6 — Future: will and going to
// ─────────────────────────────────────────────────────────────────────────────

const futureLevel: LevelInput = {
  id: 'b06',
  trackId: 'basic',
  number: 6,
  title: 'Future: will and going to',
  topic: {
    title: 'Future: will and going to',
    summary:
      'English has two common ways to talk about the future: will + base verb for predictions and spontaneous decisions, and (be) going to + base verb for plans and intentions.',
    rules: [
      {
        rule: 'future_will',
        title: 'Form: will + base verb',
        explanation:
          "Formed with will + the base verb (will go, will see). It is the same for all subjects, and the negative is won't (will not). Use it for predictions, promises, offers, and decisions made at the moment of speaking.",
        example: 'I think it will rain later. / I’ll help you carry that.',
      },
      {
        rule: 'will_vs_going_to',
        title: 'Will vs Going to',
        explanation:
          "Use be going to for plans made before the moment of speaking and for predictions based on present evidence (Look at those clouds — it's going to rain). Use will for spontaneous decisions and general predictions (I'll answer the phone).",
        example: 'We are going to move next month (plan). / The doorbell is ringing — I’ll get it (spontaneous).',
      },
    ],
  },
  questions: [
    {
      id: 'b06q01',
      levelId: 'b06',
      rule: 'future_will',
      prompt: 'Don’t worry. I ___ help you.',
      choices: ['am helping', 'will', 'will be', 'do'],
      correctIndex: 1,
      choiceExplanations: [
        "'Am helping' is wrong: the offer is made now, not an action already in progress.",
        "'Will' is correct: a spontaneous offer at the moment of speaking takes 'will'.",
        "'Will be' is wrong: 'will be help' is not a correct form — 'will' is followed by the base verb.",
        "'Do' is wrong: 'do' is present simple and does not express a future offer.",
      ],
    },
    {
      id: 'b06q02',
      levelId: 'b06',
      rule: 'future_will',
      prompt: 'I think it ___ rain this afternoon.',
      choices: ['will', 'rains', 'is raining', 'rained'],
      correctIndex: 0,
      choiceExplanations: [
        "'Will' is correct: 'I think' introduces a prediction, which takes 'will' + base verb.",
        "'Rains' is wrong: the present simple describes a habit, not a future prediction.",
        "'Is raining' is wrong: present continuous means it is raining now, not later.",
        "'Rained' is wrong: the past simple does not fit a future prediction.",
      ],
    },
    {
      id: 'b06q03',
      levelId: 'b06',
      rule: 'future_will',
      prompt: 'I promise I ___ call you tonight.',
      choices: ['am calling', 'will call', 'call', 'called'],
      correctIndex: 1,
      choiceExplanations: [
        "'Am calling' is wrong: present continuous means the call is happening now, not a promise for later.",
        "'Will call' is correct: a promise about the future takes 'will' + base verb.",
        "'Call' is wrong: the present simple does not express a future promise.",
        "'Called' is wrong: the past simple does not fit a future promise.",
      ],
    },
    {
      id: 'b06q04',
      levelId: 'b06',
      rule: 'future_will',
      prompt: '___ you open the window, please?',
      choices: ['Are', 'Do', 'Will', 'Does'],
      correctIndex: 2,
      choiceExplanations: [
        "'Are' is wrong: 'are' would need an -ing form, not the base verb 'open'.",
        "'Do' is wrong: a polite request about the future takes 'will', not 'do'.",
        "'Will' is correct: 'will' forms a polite request about the future.",
        "'Does' is wrong: 'does' is present simple and does not fit this request.",
      ],
    },
    {
      id: 'b06q05',
      levelId: 'b06',
      rule: 'will_vs_going_to',
      prompt: 'Look at those clouds! It ___ rain.',
      choices: ['will', 'is going to', 'rains', 'rained'],
      correctIndex: 1,
      choiceExplanations: [
        "'Will' is wrong: 'will' makes a general prediction, but here there is visible evidence in the clouds.",
        "'Is going to' is correct: predictions based on present evidence take 'going to'.",
        "'Rains' is wrong: the present simple does not fit a future prediction.",
        "'Rained' is wrong: the past simple does not fit a prediction about now.",
      ],
    },
    {
      id: 'b06q06',
      levelId: 'b06',
      rule: 'will_vs_going_to',
      prompt: 'I ___ a doctor when I grow up.',
      choices: ['am going to be', 'will be', 'am', 'be'],
      correctIndex: 0,
      choiceExplanations: [
        "'Am going to be' is correct: a long-held intention for the future takes 'going to'.",
        "'Will be' is wrong: 'will' suits a spontaneous decision, but this is a considered intention.",
        "'Am' is wrong: 'am' alone cannot express a future intention with 'a doctor'.",
        "'Be' is wrong: 'be' needs an auxiliary to form a future.",
      ],
    },
    {
      id: 'b06q07',
      levelId: 'b06',
      rule: 'will_vs_going_to',
      prompt: 'The phone is ringing. I ___ it!',
      choices: ['am going to answer', 'will answer', 'answer', 'answered'],
      correctIndex: 1,
      choiceExplanations: [
        "'Am going to answer' is wrong: 'going to' fits a pre-planned action, but this decision is made at the moment of speaking.",
        "'Will answer' is correct: a spontaneous decision made now takes 'will'.",
        "'Answer' is wrong: the present simple does not fit an immediate future decision.",
        "'Answered' is wrong: the past simple does not fit a future action.",
      ],
    },
    {
      id: 'b06q08',
      levelId: 'b06',
      rule: 'will_vs_going_to',
      prompt: 'We ___ dinner with friends tomorrow — we booked a table.',
      choices: ['will have', 'have', 'are going to have', 'had'],
      correctIndex: 2,
      choiceExplanations: [
        "'Will have' is wrong: the dinner was arranged before speaking, so 'going to' fits better.",
        "'Have' is wrong: the present simple does not express a future arrangement.",
        "'Are going to have' is correct: a pre-arranged plan takes 'going to'.",
        "'Had' is wrong: the past simple does not fit a future event.",
      ],
    },
    {
      id: 'b06q09',
      levelId: 'b06',
      rule: 'future_will',
      prompt: 'She ___ probably pass the exam.',
      choices: ['passes', 'will pass', 'is passing', 'passed'],
      correctIndex: 1,
      choiceExplanations: [
        "'Passes' is wrong: the present simple does not express a future prediction.",
        "'Will pass' is correct: 'probably' marks a prediction, which takes 'will'.",
        "'Is passing' is wrong: present continuous means the exam is happening now.",
        "'Passed' is wrong: the past simple does not fit a future prediction.",
      ],
    },
    {
      id: "b06q10",
      levelId: "b06",
      rule: "will_vs_going_to",
      type: 'fix_sentence',
      faultySentence: "We are going to buy a new house.",
      prompt: "It is decided: we ___ a new house.",
      choices: ["are going to buy", "will buy", "buy", "bought"],
      correctIndex: 0,
      choiceExplanations: ["'are going to buy' is correct: the sentence requires 'are going to buy'.", "'will buy' is wrong: the sentence requires 'are going to buy'.", "'buy' is wrong: the sentence requires 'are going to buy'.", "'bought' is wrong: the sentence requires 'are going to buy'."],
    },
    {
      id: "b06q11",
      levelId: "b06",
      rule: "will_vs_going_to",
      type: 'fill_blank',
      prompt: "She ___ probably pass the exam.",
      correctAnswer: "will",
      acceptedAnswers: ["will"],
      explanation: "Use will for a prediction and going to for a prior plan.",
    },
    {
      id: "b06q12",
      levelId: "b06",
      rule: "will_vs_going_to",
      type: 'word_order',
      sentenceWords: ["They", "are", "flying", "to", "Paris", "tomorrow."],
      prompt: "Arrange the words to make a correct sentence.",
      explanation: "Use will for a prediction and going to for a prior plan.",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Level 7 — Modal verbs: can, could, must, should
// ─────────────────────────────────────────────────────────────────────────────

export const basicCluster01: LevelInput[] = [
  presentSimpleLevel,
  presentContinuousLevel,
  pastSimpleLevel,
  pastContinuousLevel,
  presentPerfectLevel,
  futureLevel,
];
